#include "NeotkoFlutterDark.hpp"

#include "libslic3r/NeoDebug.hpp"

#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <map>
#include <mutex>
#include <sstream>

namespace Slic3r { namespace GUI {

// NEOTKO_FLUTTERDARK_TAG s252 — see the header for what this is and why it exists.

namespace {

// The bundle is the only file we touch. Everything else the server hands out (their
// index.html, images, fonts, the assets folder) goes through untouched.
const char* const kBundleName = "main.dart.js";

// Their service worker, and the one we hand out in its place. Tested in the real page in s252:
// the bundle asks for it, it installs, wipes Cache Storage, unregisters, and the page loads
// once — no reload loop, because it never calls clients.claim().
const char* const kServiceWorkerName = "flutter_service_worker.js";

const char* const kTombstoneServiceWorker =
    "// NEOTKO_FLUTTERDARK_TAG s252 - replaced by Neotko FullSpectrum.\n"
    "// Snapmaker's service worker cached the app and answered from that cache, which kept\n"
    "// serving the previous theme's colors. Nothing is offline here: the files are local.\n"
    "self.addEventListener('install', function (e) { self.skipWaiting(); });\n"
    "self.addEventListener('activate', function (e) {\n"
    "  e.waitUntil((async function () {\n"
    "    try {\n"
    "      var keys = await caches.keys();\n"
    "      await Promise.all(keys.map(function (k) { return caches.delete(k); }));\n"
    "    } catch (err) {}\n"
    "    try { await self.registration.unregister(); } catch (err) {}\n"
    "  })());\n"
    "});\n";

// The palette literal, as dart2js emits it: B.<name>=new A.<ColorClass>(4294967295).
//
// The class name is generated by their compiler and is renumbered on every build of theirs —
// it was A.F in bundle 2.3.25 and A.G in 2.3.30, which is exactly how this first broke in the
// field. So the class is not hardcoded: it is identified by shape, on the file in front of us.
const char* const kCtorPrefix    = "new A.";
const size_t      kCtorPrefixLen = 6;

// A palette is a class built from a single integer, hundreds of times, where most of those
// integers are fully opaque (top byte 0xFF). Both known bundles agree, and the runner-up is
// well clear: 2.3.25 → A.F 224 entries / 77% opaque (next: 138), 2.3.30 → A.G 222 / 80%.
// Classes built from a single integer that are *not* colors (269 of one kind in both files)
// come out at 0% opaque, so the alpha test is what separates them, not the count.
const int    kMinPaletteSize   = 50;
const double kMinOpaqueRatio   = 0.60;

bool ends_with(const std::string& s, const char* suffix)
{
    const size_t n = std::char_traits<char>::length(suffix);
    return s.size() >= n && s.compare(s.size() - n, n, suffix) == 0;
}

void rgb_to_hsl(double r, double g, double b, double& h, double& s, double& l)
{
    const double mx = std::max({r, g, b});
    const double mn = std::min({r, g, b});
    l              = (mx + mn) * 0.5;
    if (mx == mn) {
        h = s = 0.0; // grey: hue is meaningless
        return;
    }
    const double d = mx - mn;
    s              = l > 0.5 ? d / (2.0 - mx - mn) : d / (mx + mn);
    if (mx == r)
        h = (g - b) / d + (g < b ? 6.0 : 0.0);
    else if (mx == g)
        h = (b - r) / d + 2.0;
    else
        h = (r - g) / d + 4.0;
    h /= 6.0;
}

double hue_to_rgb(double p, double q, double t)
{
    if (t < 0.0) t += 1.0;
    if (t > 1.0) t -= 1.0;
    if (t < 1.0 / 6.0) return p + (q - p) * 6.0 * t;
    if (t < 0.5)       return q;
    if (t < 2.0 / 3.0) return p + (q - p) * (2.0 / 3.0 - t) * 6.0;
    return p;
}

void hsl_to_rgb(double h, double s, double l, double& r, double& g, double& b)
{
    if (s == 0.0) {
        r = g = b = l;
        return;
    }
    const double q = l < 0.5 ? l * (1.0 + s) : l + s - l * s;
    const double p = 2.0 * l - q;
    r              = hue_to_rgb(p, q, h + 1.0 / 3.0);
    g              = hue_to_rgb(p, q, h);
    b              = hue_to_rgb(p, q, h - 1.0 / 3.0);
}

uint8_t to_byte(double v) { return (uint8_t) std::lround(std::min(1.0, std::max(0.0, v)) * 255.0); }

// The mapping itself, tuned against the real pages in s252.
//
// Only lightness is flipped; hue and saturation are left alone, so their blue stays their
// blue instead of turning orange the way an invert filter would.
//
// Greys (the backgrounds and the text) get their flipped lightness squeezed into 0.08..0.88
// rather than 0..1: pure white must not become pure black — a page of #000 with #FFF text
// is harsh and, worse, hides the panel borders that make their layout readable.
uint32_t darken_argb(uint32_t argb)
{
    const uint32_t a = (argb >> 24) & 0xFF;
    const double   r = ((argb >> 16) & 0xFF) / 255.0;
    const double   g = ((argb >> 8) & 0xFF) / 255.0;
    const double   b = (argb & 0xFF) / 255.0;

    double h, s, l;
    rgb_to_hsl(r, g, b, h, s, l);

    double nl = 1.0 - l;
    if (s < 0.12)
        nl = 0.08 + nl * 0.80;

    double nr, ng, nb;
    hsl_to_rgb(h, s, nl, nr, ng, nb);

    return (a << 24) | ((uint32_t) to_byte(nr) << 16) | ((uint32_t) to_byte(ng) << 8) | (uint32_t) to_byte(nb);
}

bool is_ident_char(char c)
{
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '$';
}

// Walks every `new A.<ident>(<digits>)` in the file, handing each one to `visit` as
// (class name, value, offset of "new A.", offset just past the digits). Anything that is not
// exactly that shape — a variable, an expression, a number too long to be an ARGB — is skipped.
template<typename F> void scan_int_constructions(const std::string& in, F visit)
{
    size_t pos = 0;
    while (true) {
        const size_t hit = in.find(kCtorPrefix, pos);
        if (hit == std::string::npos)
            return;
        size_t p = hit + kCtorPrefixLen;

        const size_t name_begin = p;
        while (p < in.size() && is_ident_char(in[p]))
            ++p;
        const size_t name_len = p - name_begin;

        if (name_len == 0 || p >= in.size() || in[p] != '(') {
            pos = hit + kCtorPrefixLen;
            continue;
        }
        ++p;

        uint64_t     value  = 0;
        const size_t digits_begin = p;
        while (p < in.size() && in[p] >= '0' && in[p] <= '9' && (p - digits_begin) < 10) {
            value = value * 10 + (uint64_t)(in[p] - '0');
            ++p;
        }
        if (p == digits_begin || p >= in.size() || in[p] != ')' || value > 0xFFFFFFFFull) {
            pos = hit + kCtorPrefixLen;
            continue;
        }

        visit(in.substr(name_begin, name_len), (uint32_t) value, hit, p);
        pos = p;
    }
}

// Picks the class that holds the palette, on this exact file. Returns an empty string when
// nothing looks like one, which is the signal to serve their bundle untouched.
std::string detect_palette_class(const std::string& in, int& out_count)
{
    struct Tally { int count = 0; int opaque = 0; };
    std::map<std::string, Tally> tallies;

    scan_int_constructions(in, [&tallies](const std::string& name, uint32_t value, size_t, size_t) {
        Tally& t = tallies[name];
        ++t.count;
        if ((value >> 24) == 0xFF)
            ++t.opaque;
    });

    std::string best;
    int         best_count = 0;
    for (const auto& kv : tallies) {
        const Tally& t = kv.second;
        if (t.count < kMinPaletteSize || (double) t.opaque / (double) t.count < kMinOpaqueRatio)
            continue;
        if (t.count > best_count) {
            best       = kv.first;
            best_count = t.count;
        }
    }
    out_count = best_count;
    return best;
}

// Rewrites every palette literal of the given class. Returns how many colors were converted.
int build_dark_bundle(const std::string& in, const std::string& palette_class, std::string& out)
{
    out.clear();
    out.reserve(in.size() + in.size() / 64);

    int    converted = 0;
    size_t copied    = 0; // everything before this offset is already in `out`

    scan_int_constructions(in, [&](const std::string& name, uint32_t value, size_t begin, size_t end) {
        if (name != palette_class)
            return;
        // Copy up to and including "new A.<name>(", then the darkened integer. The ')' at `end`
        // is left for the next chunk.
        out.append(in, copied, (begin + kCtorPrefixLen + name.size() + 1) - copied);
        out += std::to_string(darken_argb(value));
        copied = end;
        ++converted;
    });
    out.append(in, copied, std::string::npos);

    return converted;
}

// NEOTKO_FLUTTERDARK_TAG s252 — silent unless asked for. It was written unconditionally while a
// field report was open and it is what closed it: one line named the class we picked and the
// bundle version the reporter actually had. Kept, gated, because their bundle updates itself on
// each user's machine, so the next surprise will arrive the same way.
//   export ORCA_DEBUG_FLUTTERDARK=1   →  /tmp/neotko_flutterdark.log
void log(const std::string& msg)
{
    if (NeoDebug::enabled(NeoDebug::FLUTTERDARK))
        NeoDebug::write(NeoDebug::FLUTTERDARK, msg);
}

// The bundle's sibling version.json says which build of their app this user actually has —
// the one thing that differs between two machines on the same Orca and the same OS, since the
// bundle lives in the user's own profile and updates itself from Snapmaker's server.
std::string read_bundle_version(const std::string& bundle_path)
{
    const size_t slash = bundle_path.find_last_of("/\\");
    if (slash == std::string::npos)
        return "<no dir>";
    std::ifstream f(bundle_path.substr(0, slash + 1) + "version.json", std::ios::binary);
    if (!f)
        return "<version.json missing>";
    std::ostringstream ss;
    ss << f.rdbuf();
    std::string v = ss.str();
    // Keep it to one log line.
    for (char& c : v)
        if (c == '\n' || c == '\r')
            c = ' ';
    return v.size() > 300 ? v.substr(0, 300) + "..." : v;
}

std::atomic<bool> g_dark{false};

// One cached dark bundle. Keyed by the source we derived it from, so a Snapmaker update
// (new size, new content) rebuilds instead of serving a stale one.
std::mutex  g_cache_mutex;
std::string g_cache_out;
size_t      g_cache_src_size  = 0;
size_t      g_cache_src_hash  = 0;
bool        g_cache_src_known = false;
bool        g_cache_usable    = false;

} // namespace

void NeotkoFlutterDark::set_dark(bool dark)
{
    g_dark.store(dark, std::memory_order_relaxed);
    // Diagnostic: if this never says 1, nothing downstream matters — the app does not consider
    // itself dark, and on macOS that is the OS appearance and nothing else. Logged on every
    // call rather than on change, so "light" and "never ran" cannot look the same in the log.
    log(std::string("[theme] dark=") + (dark ? "1" : "0"));
}

bool NeotkoFlutterDark::is_dark() { return g_dark.load(std::memory_order_relaxed); }

bool NeotkoFlutterDark::must_not_be_cached(const std::string& file_path)
{
    return ends_with(file_path, kBundleName) || ends_with(file_path, kServiceWorkerName);
}

bool NeotkoFlutterDark::neutralize_service_worker(const std::string& file_path, std::string& content)
{
    if (!ends_with(file_path, kServiceWorkerName))
        return false;
    // Diagnostic: proves their worker was asked for and replaced. If the page is stale and this
    // line is absent, the page never reached our server at all.
    log("[sw] replaced theirs (" + std::to_string(content.size()) + " bytes) with the tombstone");
    content = kTombstoneServiceWorker;
    return true;
}

bool NeotkoFlutterDark::maybe_patch(const std::string& file_path, std::string& content)
{
    if (!ends_with(file_path, kBundleName))
        return false;

    // NEOTKO_FLUTTERDARK_TAG s252 — diagnostic. Logged before the dark check so a machine that
    // renders light still says why: reaching this line at all proves the request came to us and
    // was not answered from a cache or a service worker.
    log("[bundle] dark=" + std::string(is_dark() ? "1" : "0") + " size=" + std::to_string(content.size()) +
        " path=" + file_path);

    if (!is_dark() || content.empty())
        return false;

    // Cheap identity for the source: its size plus a hash. Content is what we key on rather
    // than the file's timestamp, because an update rewrites the file in place and we would
    // rather rebuild once too often than serve the previous version's colors.
    const size_t src_size = content.size();
    const size_t src_hash = std::hash<std::string>{}(content);

    std::lock_guard<std::mutex> lock(g_cache_mutex);
    if (!(g_cache_src_known && g_cache_src_size == src_size && g_cache_src_hash == src_hash)) {
        int               detected_count = 0;
        const std::string palette_class  = detect_palette_class(content, detected_count);

        std::string patched;
        const int   converted = palette_class.empty() ? 0 : build_dark_bundle(content, palette_class, patched);

        // Diagnostic: the decisive line. Their bundle updates itself per user and the class name
        // is renumbered on every build of theirs, so this records which one we settled on here.
        log("[palette] class=" + (palette_class.empty() ? std::string("<none>") : "A." + palette_class) +
            " converted=" + std::to_string(converted) + " verdict=" + (converted > 0 ? "PATCHED" : "LEFT LIGHT") +
            " bundle_version=" + read_bundle_version(file_path));

        g_cache_src_size  = src_size;
        g_cache_src_hash  = src_hash;
        g_cache_src_known = true;
        g_cache_usable    = converted > 0;
        g_cache_out       = g_cache_usable ? std::move(patched) : std::string();
    }

    // Palette not recognized: hand back their file untouched and let the page render light.
    // Tinting is a nicety; breaking the only way to drive the printer is not an option.
    if (!g_cache_usable)
        return false;

    content = g_cache_out;
    return true;
}

}} // namespace Slic3r::GUI
